from tkinter import *
tk = Tk()
tk.geometry("700x1000")
frame = Frame(tk, bg="#ebf2fa",width=700,height=1000)
frame.place(x=0,y=0)
title = Label(frame, text="Input your statistics!", font=("Franklin Gothic Demi Cond",60),fg="#679436",bg="#ebf2fa")
title.place(x=350,y=100,anchor="center")
driving=Label(frame,text="Miles driven today", font=("Franklin Gothic Demi Cond",25), fg="#427aa1",bg="#ebf2fa")
driving.place(x=50,y=240,anchor="w")
drivingInput=Entry()
drivingInput.place(x=300,y=240,anchor="w")
water=Label(frame,text="Water used",font=("Franklin Gothic Demi Cond",25), fg="#427aa1",bg="#ebf2fa")
water.place(x=50,y=340,anchor="w")
waterInput=Entry()
waterInput.place(x=300,y=340,anchor="w")
meat=Label(frame, text="Meat eaten",font=("Franklin Gothic Demi Cond",25), fg="#427aa1",bg="#ebf2fa")
energyUsed=Label(frame, text="Energy used",font=("Franklin Gothic Demi Cond",25), fg="#427aa1",bg="#ebf2fa")
energyUsed.place(x=50,y=440,anchor="w")
energyInput=Entry()
energyInput.place(x=300,y=440,anchor="w")
meat.place(x=50,y=540,anchor="w")
meatEatenInput=Entry()
meatEatenInput.place(x=300,y=540,anchor="w")
tk.mainloop()

